name: my_first_website
description: My first website to practice flutter with a real example that can get me some extra bucks
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_builder: ^0.4.3
  firebase_core: ^2.6.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
  fonts:
  - family: Open Sans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 400
      - asset: assets/fonts/OpenSans-Italic.ttf
        weight: 400