// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpR5bl8wveLVphoj94rG7xxQqeZxVx-w',
    appId: '1:826410718011:web:d7437fb72b1038b0e71d1e',
    messagingSenderId: '826410718011',
    projectId: 'gustavo-website',
    authDomain: 'gustavo-website.firebaseapp.com',
    storageBucket: 'gustavo-website.appspot.com',
    measurementId: 'G-MV6JJ4C6QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoN23M8D4ZdwKLMzAvhNgmbIqf5rJmadc',
    appId: '1:826410718011:android:13cfe093ff4df87de71d1e',
    messagingSenderId: '826410718011',
    projectId: 'gustavo-website',
    storageBucket: 'gustavo-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY_-hjPq6WVRcgKbTjTCNjCea5f_kdLeQ',
    appId: '1:826410718011:ios:4511cc90088b180ee71d1e',
    messagingSenderId: '826410718011',
    projectId: 'gustavo-website',
    storageBucket: 'gustavo-website.appspot.com',
    iosClientId:
        '826410718011-g6u0nndf182iouic4ls2cnpm32m29ff5.apps.googleusercontent.com',
    iosBundleId: 'com.gustavoramos.myFirstWebsite',
  );
}
